### ISSUE TITLE
اندروید 8 ساپورت نمیشه

### ISSUE THREAD

**Issue by Arashvscode** [Arashvscode/GhostWeb_IDE#1]
```java.lang.RuntimeException: Unable to start activity ComponentInfo{Ninja.coder.Ghostemane.code/Ninja.coder.Ghostemane.code.MainActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6942)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
	at android.app.Activity.onCreate(Activity.java:1038)
	at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:85)
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:314)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
	at Ninja.coder.Ghostemane.code.MainActivity.onCreate(MainActivity.java:62)
	at android.app.Activity.performCreate(Activity.java:7183)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1221)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
	... 9 more```


کاربر نمیتواند کشش ایجاد کند

**Comment by xp-amiralidashti** [comment]
https://user-images.githubusercontent.com/80316142/183058935-5e346216-cdec-45b4-99fe-bb21b20f93e3.mp4

**Comment by Arashvscode** [comment]
> XRecorder_05082022_145732.mp4

اندروید 10 خوب کار میکنع
